setwd("/cellranger_results_goat_V1/")

library(Seurat)
library(dplyr)
library(patchwork)
library(cowplot)
library(ggplot2)

#### e45 pretreatment ###
#### Setup the Seurat objects ###

e45.data <- Read10X(data.dir = "/cellranger_results_goat_V1/e45/")
e45 <- CreateSeuratObject(counts = e45.data, project = "e45", min.cells = 3, min.features = 200)
samInfo <- rep("e45",nrow(e45@meta.data))
e45 <- AddMetaData(object = e45, metadata = samInfo, col.name = "samInfo")
e45[["ND6"]] <- PercentageFeatureSet(e45, assay = "RNA", feature = "ND6")
e45[["ND5"]] <- PercentageFeatureSet(e45, assay = "RNA", feature = "ND5")
e45[["ND4L"]] <- PercentageFeatureSet(e45, assay = "RNA", feature = "ND4L")
e45[["ND4"]] <- PercentageFeatureSet(e45, assay = "RNA", feature = "ND4")
e45[["ND3"]] <- PercentageFeatureSet(e45, assay = "RNA", feature = "ND3")
e45[["ND2"]] <- PercentageFeatureSet(e45, assay = "RNA", feature = "ND2")
e45[["ND1"]] <- PercentageFeatureSet(e45, assay = "RNA", feature = "ND1")
e45[["CYTB"]] <- PercentageFeatureSet(e45, assay = "RNA", feature = "CYTB")
e45[["COX3"]] <- PercentageFeatureSet(e45, assay = "RNA", feature = "COX3")
e45[["COX2"]] <- PercentageFeatureSet(e45, assay = "RNA", feature = "COX2")
e45[["COX1"]] <- PercentageFeatureSet(e45, assay = "RNA", feature = "COX1")
e45[["ATP8"]] <- PercentageFeatureSet(e45, assay = "RNA", feature = "ATP8")
e45[["ATP6"]] <- PercentageFeatureSet(e45, assay = "RNA", feature = "ATP6")
e45[["percent.mt"]] <- apply(e45@meta.data[,5:15], 1, sum)
VlnPlot(e45, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
e45 <- subset(e45, subset = nFeature_RNA > 200 & nFeature_RNA < 3500 & percent.mt < 40)
plot1 <- FeatureScatter(e45, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(e45, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
e45 <- NormalizeData(e45, normalization.method = "LogNormalize", scale.factor = 10000)
e45 <- FindVariableFeatures(e45, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(e45)
e45 <- ScaleData(e45, features = all.genes)
e45 <- ScaleData(e45, vars.to.regress = "percent.mt")
e45 <- RunPCA(e45, features = VariableFeatures(object = e45))
ElbowPlot(e45, ndim=50)
e45 <- FindNeighbors(e45, dims = 1:30)
e45 <- FindClusters(e45, resolution = 0.6)
e45 <- RunTSNE(e45, dims = 1:30)
DimPlot(e45,reduction = "tsne",label = TRUE, pt.size = 1.5)
e45<- CellCycleScoring(object = e45, g2m.features = cc.genes$g2m.genes, s.features = cc.genes$s.genes)
head(x = e45@meta.data)
DimPlot(e45,reduction = "tsne",label = TRUE,group.by="Phase",pt.size = 1.5)

######Removal of double cells####
library(DoubletFinder)

sweep.res.list_e45 <- paramSweep_v3(e45, PCs = 1:30, sct = FALSE)
sweep.stats_e45 <- summarizeSweep(sweep.res.list_e45, GT = FALSE)
bcmvn_e45 <- find.pK(sweep.stats_e45)
opt_pK <- as.numeric(as.vector(bcmvn_e45$pK[which.max(bcmvn_e45$BCmetric)]))
print(opt_pK)
annotations <- e45@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)
nExp_poi <- round(0.06*nrow(e45@meta.data))
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
e45 <- doubletFinder_v3(e45,PCs = 1:30,pN = 0.25,pK = opt_pK,nExp = nExp_poi,reuse.pANN = FALSE,sct = FALSE)
name <- colnames(e45@meta.data)[7]
Idents(e45) <- name
e45 <- subset(e45, idents = "Singlet")
saveRDS(e45, file = "e45_goat_clean.rds")

#### e60 pretreatment ###
#### Setup the Seurat objects ###

e60.data <- Read10X(data.dir = "/cellranger_results_goat_V1/e60/")
e60 <- CreateSeuratObject(counts = e60.data, project = "e60", min.cells = 3, min.features = 200)
samInfo <- rep("e60",nrow(e60@meta.data))
e60 <- AddMetaData(object = e60, metadata = samInfo, col.name = "samInfo")
e60[["ND6"]] <- PercentageFeatureSet(e60, assay = "RNA", feature = "ND6")
e60[["ND5"]] <- PercentageFeatureSet(e60, assay = "RNA", feature = "ND5")
e60[["ND4L"]] <- PercentageFeatureSet(e60, assay = "RNA", feature = "ND4L")
e60[["ND4"]] <- PercentageFeatureSet(e60, assay = "RNA", feature = "ND4")
e60[["ND3"]] <- PercentageFeatureSet(e60, assay = "RNA", feature = "ND3")
e60[["ND2"]] <- PercentageFeatureSet(e60, assay = "RNA", feature = "ND2")
e60[["ND1"]] <- PercentageFeatureSet(e60, assay = "RNA", feature = "ND1")
e60[["CYTB"]] <- PercentageFeatureSet(e60, assay = "RNA", feature = "CYTB")
e60[["COX3"]] <- PercentageFeatureSet(e60, assay = "RNA", feature = "COX3")
e60[["COX2"]] <- PercentageFeatureSet(e60, assay = "RNA", feature = "COX2")
e60[["COX1"]] <- PercentageFeatureSet(e60, assay = "RNA", feature = "COX1")
e60[["ATP8"]] <- PercentageFeatureSet(e60, assay = "RNA", feature = "ATP8")
e60[["ATP6"]] <- PercentageFeatureSet(e60, assay = "RNA", feature = "ATP6")
e60[["percent.mt"]] <- apply(e60@meta.data[,5:15], 1, sum)
VlnPlot(e60, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
e60 <- subset(e60, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 50)
plot1 <- FeatureScatter(e60, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(e60, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
e60 <- NormalizeData(e60, normalization.method = "LogNormalize", scale.factor = 10000)
e60 <- FindVariableFeatures(e60, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(e60)
e60 <- ScaleData(e60, features = all.genes)
e60 <- ScaleData(e60, vars.to.regress = "percent.mt")
e60 <- RunPCA(e60, features = VariableFeatures(object = e60))
ElbowPlot(e60, ndim=50)
e60 <- FindNeighbors(e60, dims = 1:30)
e60 <- FindClusters(e60, resolution = 0.6)
e60 <- RunTSNE(e60, dims = 1:30)
DimPlot(e60,reduction = "tsne",label = TRUE, pt.size = 1.5)
e60<- CellCycleScoring(object = e60, g2m.features = cc.genes$g2m.genes, s.features = cc.genes$s.genes)
head(x = e60@meta.data)
DimPlot(e60,reduction = "tsne",label = TRUE,group.by="Phase",pt.size = 1.5)

######Removal of double cells####
library(DoubletFinder)

sweep.res.list_e60 <- paramSweep_v3(e60, PCs = 1:30, sct = FALSE)
sweep.stats_e60 <- summarizeSweep(sweep.res.list_e60, GT = FALSE)
bcmvn_e60 <- find.pK(sweep.stats_e60)
opt_pK <- as.numeric(as.vector(bcmvn_e60$pK[which.max(bcmvn_e60$BCmetric)]))
print(opt_pK)
annotations <- e60@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)
nExp_poi <- round(0.06*nrow(e60@meta.data))
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
e60 <- doubletFinder_v3(e60,PCs = 1:30,pN = 0.25,pK = opt_pK,nExp = nExp_poi,reuse.pANN = FALSE,sct = FALSE)
name <- colnames(e60@meta.data)[7]
Idents(e60) <- name
e60 <- subset(e60, idents = "Singlet")
saveRDS(e60, file = "e60_goat_clean.rds")

#### e75 pretreatment ###
#### Setup the Seurat objects ###

e75.data <- Read10X(data.dir = "/cellranger_results_goat_V1/e75/")
e75 <- CreateSeuratObject(counts = e75.data, project = "e75", min.cells = 3, min.features = 200)
samInfo <- rep("e75",nrow(e75@meta.data))
e75 <- AddMetaData(object = e75, metadata = samInfo, col.name = "samInfo")
e75[["ND6"]] <- PercentageFeatureSet(e75, assay = "RNA", feature = "ND6")
e75[["ND5"]] <- PercentageFeatureSet(e75, assay = "RNA", feature = "ND5")
e75[["ND4L"]] <- PercentageFeatureSet(e75, assay = "RNA", feature = "ND4L")
e75[["ND4"]] <- PercentageFeatureSet(e75, assay = "RNA", feature = "ND4")
e75[["ND3"]] <- PercentageFeatureSet(e75, assay = "RNA", feature = "ND3")
e75[["ND2"]] <- PercentageFeatureSet(e75, assay = "RNA", feature = "ND2")
e75[["ND1"]] <- PercentageFeatureSet(e75, assay = "RNA", feature = "ND1")
e75[["CYTB"]] <- PercentageFeatureSet(e75, assay = "RNA", feature = "CYTB")
e75[["COX3"]] <- PercentageFeatureSet(e75, assay = "RNA", feature = "COX3")
e75[["COX2"]] <- PercentageFeatureSet(e75, assay = "RNA", feature = "COX2")
e75[["COX1"]] <- PercentageFeatureSet(e75, assay = "RNA", feature = "COX1")
e75[["ATP8"]] <- PercentageFeatureSet(e75, assay = "RNA", feature = "ATP8")
e75[["ATP6"]] <- PercentageFeatureSet(e75, assay = "RNA", feature = "ATP6")
e75[["percent.mt"]] <- apply(e75@meta.data[,5:15], 1, sum)
VlnPlot(e75, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
e75 <- subset(e75, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 50)
plot1 <- FeatureScatter(e75, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(e75, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
e75 <- NormalizeData(e75, normalization.method = "LogNormalize", scale.factor = 10000)
e75 <- FindVariableFeatures(e75, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(e75)
e75 <- ScaleData(e75, features = all.genes)
e75 <- ScaleData(e75, vars.to.regress = "percent.mt")
e75 <- RunPCA(e75, features = VariableFeatures(object = e75))
ElbowPlot(e75, ndim=50)
e75 <- FindNeighbors(e75, dims = 1:30)
e75 <- FindClusters(e75, resolution = 0.6)
e75 <- RunTSNE(e75, dims = 1:30)
DimPlot(e75,reduction = "tsne",label = TRUE, pt.size = 1.5)
e75<- CellCycleScoring(object = e75, g2m.features = cc.genes$g2m.genes, s.features = cc.genes$s.genes)
head(x = e75@meta.data)
DimPlot(e75,reduction = "tsne",label = TRUE,group.by="Phase",pt.size = 1.5)

######Removal of double cells####
library(DoubletFinder)

sweep.res.list_e75 <- paramSweep_v3(e75, PCs = 1:30, sct = FALSE)
sweep.stats_e75 <- summarizeSweep(sweep.res.list_e75, GT = FALSE)
bcmvn_e75 <- find.pK(sweep.stats_e75)
opt_pK <- as.numeric(as.vector(bcmvn_e75$pK[which.max(bcmvn_e75$BCmetric)]))
print(opt_pK)
annotations <- e75@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)
nExp_poi <- round(0.06*nrow(e75@meta.data))
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
e75 <- doubletFinder_v3(e75,PCs = 1:30,pN = 0.25,pK = opt_pK,nExp = nExp_poi,reuse.pANN = FALSE,sct = FALSE)
name <- colnames(e75@meta.data)[7]
Idents(e75) <- name
e75 <- subset(e75, idents = "Singlet")
saveRDS(e75, file = "e75_goat_clean.rds")

#### e90 pretreatment ###
#### Setup the Seurat objects ###

e90.data <- Read10X(data.dir = "/cellranger_results_goat_V1/e90/")
e90 <- CreateSeuratObject(counts = e90.data, project = "e90", min.cells = 3, min.features = 200)
samInfo <- rep("e90",nrow(e90@meta.data))
e90 <- AddMetaData(object = e90, metadata = samInfo, col.name = "samInfo")
e90[["ND6"]] <- PercentageFeatureSet(e90, assay = "RNA", feature = "ND6")
e90[["ND5"]] <- PercentageFeatureSet(e90, assay = "RNA", feature = "ND5")
e90[["ND4L"]] <- PercentageFeatureSet(e90, assay = "RNA", feature = "ND4L")
e90[["ND4"]] <- PercentageFeatureSet(e90, assay = "RNA", feature = "ND4")
e90[["ND3"]] <- PercentageFeatureSet(e90, assay = "RNA", feature = "ND3")
e90[["ND2"]] <- PercentageFeatureSet(e90, assay = "RNA", feature = "ND2")
e90[["ND1"]] <- PercentageFeatureSet(e90, assay = "RNA", feature = "ND1")
e90[["CYTB"]] <- PercentageFeatureSet(e90, assay = "RNA", feature = "CYTB")
e90[["COX3"]] <- PercentageFeatureSet(e90, assay = "RNA", feature = "COX3")
e90[["COX2"]] <- PercentageFeatureSet(e90, assay = "RNA", feature = "COX2")
e90[["COX1"]] <- PercentageFeatureSet(e90, assay = "RNA", feature = "COX1")
e90[["ATP8"]] <- PercentageFeatureSet(e90, assay = "RNA", feature = "ATP8")
e90[["ATP6"]] <- PercentageFeatureSet(e90, assay = "RNA", feature = "ATP6")
e90[["percent.mt"]] <- apply(e90@meta.data[,5:15], 1, sum)
VlnPlot(e90, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
e90 <- subset(e90, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 50 & nCount < 50000)
plot1 <- FeatureScatter(e90, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(e90, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
e90 <- NormalizeData(e90, normalization.method = "LogNormalize", scale.factor = 10000)
e90 <- FindVariableFeatures(e90, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(e90)
e90 <- ScaleData(e90, features = all.genes)
e90 <- ScaleData(e90, vars.to.regress = "percent.mt")
e90 <- RunPCA(e90, features = VariableFeatures(object = e90))
ElbowPlot(e90, ndim=50)
e90 <- FindNeighbors(e90, dims = 1:30)
e90 <- FindClusters(e90, resolution = 0.6)
e90 <- RunTSNE(e90, dims = 1:30)
DimPlot(e90,reduction = "tsne",label = TRUE, pt.size = 1.5)
e90<- CellCycleScoring(object = e90, g2m.features = cc.genes$g2m.genes, s.features = cc.genes$s.genes)
head(x = e90@meta.data)
DimPlot(e90,reduction = "tsne",label = TRUE,group.by="Phase",pt.size = 1.5)

######Removal of double cells####
library(DoubletFinder)

sweep.res.list_e90 <- paramSweep_v3(e90, PCs = 1:30, sct = FALSE)
sweep.stats_e90 <- summarizeSweep(sweep.res.list_e90, GT = FALSE)
bcmvn_e90 <- find.pK(sweep.stats_e90)
opt_pK <- as.numeric(as.vector(bcmvn_e90$pK[which.max(bcmvn_e90$BCmetric)]))
print(opt_pK)
annotations <- e90@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)
nExp_poi <- round(0.06*nrow(e90@meta.data))
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
e90 <- doubletFinder_v3(e90,PCs = 1:30,pN = 0.25,pK = opt_pK,nExp = nExp_poi,reuse.pANN = FALSE,sct = FALSE)
name <- colnames(e90@meta.data)[7]
Idents(e90) <- name
e90 <- subset(e90, idents = "Singlet")
saveRDS(e90, file = "e90_goat_clean.rds")

#### e105 pretreatment ###
#### Setup the Seurat objects ###

e105.data <- Read10X(data.dir = "/cellranger_results_goat_V1/e105/")
e105 <- CreateSeuratObject(counts = e105.data, project = "e105", min.cells = 3, min.features = 200)
samInfo <- rep("e105",nrow(e105@meta.data))
e105 <- AddMetaData(object = e105, metadata = samInfo, col.name = "samInfo")
e105[["ND6"]] <- PercentageFeatureSet(e105, assay = "RNA", feature = "ND6")
e105[["ND5"]] <- PercentageFeatureSet(e105, assay = "RNA", feature = "ND5")
e105[["ND4L"]] <- PercentageFeatureSet(e105, assay = "RNA", feature = "ND4L")
e105[["ND4"]] <- PercentageFeatureSet(e105, assay = "RNA", feature = "ND4")
e105[["ND3"]] <- PercentageFeatureSet(e105, assay = "RNA", feature = "ND3")
e105[["ND2"]] <- PercentageFeatureSet(e105, assay = "RNA", feature = "ND2")
e105[["ND1"]] <- PercentageFeatureSet(e105, assay = "RNA", feature = "ND1")
e105[["CYTB"]] <- PercentageFeatureSet(e105, assay = "RNA", feature = "CYTB")
e105[["COX3"]] <- PercentageFeatureSet(e105, assay = "RNA", feature = "COX3")
e105[["COX2"]] <- PercentageFeatureSet(e105, assay = "RNA", feature = "COX2")
e105[["COX1"]] <- PercentageFeatureSet(e105, assay = "RNA", feature = "COX1")
e105[["ATP8"]] <- PercentageFeatureSet(e105, assay = "RNA", feature = "ATP8")
e105[["ATP6"]] <- PercentageFeatureSet(e105, assay = "RNA", feature = "ATP6")
e105[["percent.mt"]] <- apply(e105@meta.data[,5:15], 1, sum)
VlnPlot(e105, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
e105 <- subset(e105, subset = nFeature_RNA > 200 & nFeature_RNA < 3500 & percent.mt < 40)
plot1 <- FeatureScatter(e105, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(e105, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
e105 <- NormalizeData(e105, normalization.method = "LogNormalize", scale.factor = 10000)
e105 <- FindVariableFeatures(e105, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(e105)
e105 <- ScaleData(e105, features = all.genes)
e105 <- ScaleData(e105, vars.to.regress = "percent.mt")
e105 <- RunPCA(e105, features = VariableFeatures(object = e105))
ElbowPlot(e105, ndim=50)
e105 <- FindNeighbors(e105, dims = 1:30)
e105 <- FindClusters(e105, resolution = 0.6)
e105 <- RunTSNE(e105, dims = 1:30)
DimPlot(e105,reduction = "tsne",label = TRUE, pt.size = 1.5)
e105<- CellCycleScoring(object = e105, g2m.features = cc.genes$g2m.genes, s.features = cc.genes$s.genes)
head(x = e105@meta.data)
DimPlot(e105,reduction = "tsne",label = TRUE,group.by="Phase",pt.size = 1.5)

######Removal of double cells####
library(DoubletFinder)

sweep.res.list_e105 <- paramSweep_v3(e105, PCs = 1:30, sct = FALSE)
sweep.stats_e105 <- summarizeSweep(sweep.res.list_e105, GT = FALSE)
bcmvn_e105 <- find.pK(sweep.stats_e105)
opt_pK <- as.numeric(as.vector(bcmvn_e105$pK[which.max(bcmvn_e105$BCmetric)]))
print(opt_pK)
annotations <- e105@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)
nExp_poi <- round(0.06*nrow(e105@meta.data))
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
e105 <- doubletFinder_v3(e105,PCs = 1:30,pN = 0.25,pK = opt_pK,nExp = nExp_poi,reuse.pANN = FALSE,sct = FALSE)
name <- colnames(e105@meta.data)[7]
Idents(e105) <- name
e105 <- subset(e105, idents = "Singlet")
saveRDS(e105, file = "e105_goat_clean.rds")

#### e120 pretreatment ###
#### Setup the Seurat objects ###

e120.data <- Read10X(data.dir = "/cellranger_results_goat_V1/e120/")
e120 <- CreateSeuratObject(counts = e120.data, project = "e120", min.cells = 3, min.features = 200)
samInfo <- rep("e120",nrow(e120@meta.data))
e120 <- AddMetaData(object = e120, metadata = samInfo, col.name = "samInfo")
e120[["ND6"]] <- PercentageFeatureSet(e120, assay = "RNA", feature = "ND6")
e120[["ND5"]] <- PercentageFeatureSet(e120, assay = "RNA", feature = "ND5")
e120[["ND4L"]] <- PercentageFeatureSet(e120, assay = "RNA", feature = "ND4L")
e120[["ND4"]] <- PercentageFeatureSet(e120, assay = "RNA", feature = "ND4")
e120[["ND3"]] <- PercentageFeatureSet(e120, assay = "RNA", feature = "ND3")
e120[["ND2"]] <- PercentageFeatureSet(e120, assay = "RNA", feature = "ND2")
e120[["ND1"]] <- PercentageFeatureSet(e120, assay = "RNA", feature = "ND1")
e120[["CYTB"]] <- PercentageFeatureSet(e120, assay = "RNA", feature = "CYTB")
e120[["COX3"]] <- PercentageFeatureSet(e120, assay = "RNA", feature = "COX3")
e120[["COX2"]] <- PercentageFeatureSet(e120, assay = "RNA", feature = "COX2")
e120[["COX1"]] <- PercentageFeatureSet(e120, assay = "RNA", feature = "COX1")
e120[["ATP8"]] <- PercentageFeatureSet(e120, assay = "RNA", feature = "ATP8")
e120[["ATP6"]] <- PercentageFeatureSet(e120, assay = "RNA", feature = "ATP6")
e120[["percent.mt"]] <- apply(e120@meta.data[,5:15], 1, sum)
VlnPlot(e120, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
e120 <- subset(e120, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 40)
plot1 <- FeatureScatter(e120, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(e120, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
e120 <- NormalizeData(e120, normalization.method = "LogNormalize", scale.factor = 10000)
e120 <- FindVariableFeatures(e120, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(e120)
e120 <- ScaleData(e120, features = all.genes)
e120 <- ScaleData(e120, vars.to.regress = "percent.mt")
e120 <- RunPCA(e120, features = VariableFeatures(object = e120))
ElbowPlot(e120, ndim=50)
e120 <- FindNeighbors(e120, dims = 1:30)
e120 <- FindClusters(e120, resolution = 0.6)
e120 <- RunTSNE(e120, dims = 1:30)
DimPlot(e120,reduction = "tsne",label = TRUE, pt.size = 1.5)
e120<- CellCycleScoring(object = e120, g2m.features = cc.genes$g2m.genes, s.features = cc.genes$s.genes)
head(x = e120@meta.data)
DimPlot(e120,reduction = "tsne",label = TRUE,group.by="Phase",pt.size = 1.5)

######Removal of double cells####
library(DoubletFinder)

sweep.res.list_e120 <- paramSweep_v3(e120, PCs = 1:30, sct = FALSE)
sweep.stats_e120 <- summarizeSweep(sweep.res.list_e120, GT = FALSE)
bcmvn_e120 <- find.pK(sweep.stats_e120)
opt_pK <- as.numeric(as.vector(bcmvn_e120$pK[which.max(bcmvn_e120$BCmetric)]))
print(opt_pK)
annotations <- e120@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)
nExp_poi <- round(0.06*nrow(e120@meta.data))
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
e120 <- doubletFinder_v3(e120,PCs = 1:30,pN = 0.25,pK = opt_pK,nExp = nExp_poi,reuse.pANN = FALSE,sct = FALSE)
name <- colnames(e120@meta.data)[7]
Idents(e120) <- name
e120 <- subset(e120, idents = "Singlet")
saveRDS(e120, file = "e120_goat_clean.rds")

#### e135 pretreatment ###
#### Setup the Seurat objects ###

e135.data <- Read10X(data.dir = "/cellranger_results_goat_V1/e135/")
e135 <- CreateSeuratObject(counts = e135.data, project = "e135", min.cells = 3, min.features = 200)
samInfo <- rep("e135",nrow(e135@meta.data))
e135 <- AddMetaData(object = e135, metadata = samInfo, col.name = "samInfo")
e135[["ND6"]] <- PercentageFeatureSet(e135, assay = "RNA", feature = "ND6")
e135[["ND5"]] <- PercentageFeatureSet(e135, assay = "RNA", feature = "ND5")
e135[["ND4L"]] <- PercentageFeatureSet(e135, assay = "RNA", feature = "ND4L")
e135[["ND4"]] <- PercentageFeatureSet(e135, assay = "RNA", feature = "ND4")
e135[["ND3"]] <- PercentageFeatureSet(e135, assay = "RNA", feature = "ND3")
e135[["ND2"]] <- PercentageFeatureSet(e135, assay = "RNA", feature = "ND2")
e135[["ND1"]] <- PercentageFeatureSet(e135, assay = "RNA", feature = "ND1")
e135[["CYTB"]] <- PercentageFeatureSet(e135, assay = "RNA", feature = "CYTB")
e135[["COX3"]] <- PercentageFeatureSet(e135, assay = "RNA", feature = "COX3")
e135[["COX2"]] <- PercentageFeatureSet(e135, assay = "RNA", feature = "COX2")
e135[["COX1"]] <- PercentageFeatureSet(e135, assay = "RNA", feature = "COX1")
e135[["ATP8"]] <- PercentageFeatureSet(e135, assay = "RNA", feature = "ATP8")
e135[["ATP6"]] <- PercentageFeatureSet(e135, assay = "RNA", feature = "ATP6")
e135[["percent.mt"]] <- apply(e135@meta.data[,5:15], 1, sum)
VlnPlot(e135, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
e135 <- subset(e135, subset = nFeature_RNA > 200 & nFeature_RNA < 3500 & percent.mt < 50)
plot1 <- FeatureScatter(e135, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(e135, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
e135 <- NormalizeData(e135, normalization.method = "LogNormalize", scale.factor = 10000)
e135 <- FindVariableFeatures(e135, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(e135)
e135 <- ScaleData(e135, features = all.genes)
e135 <- ScaleData(e135, vars.to.regress = "percent.mt")
e135 <- RunPCA(e135, features = VariableFeatures(object = e135))
ElbowPlot(e135, ndim=50)
e135 <- FindNeighbors(e135, dims = 1:30)
e135 <- FindClusters(e135, resolution = 0.6)
e135 <- RunTSNE(e135, dims = 1:30)
DimPlot(e135,reduction = "tsne",label = TRUE, pt.size = 1.5)
e135<- CellCycleScoring(object = e135, g2m.features = cc.genes$g2m.genes, s.features = cc.genes$s.genes)
head(x = e135@meta.data)
DimPlot(e135,reduction = "tsne",label = TRUE,group.by="Phase",pt.size = 1.5)

######Removal of double cells####
library(DoubletFinder)

sweep.res.list_e135 <- paramSweep_v3(e135, PCs = 1:30, sct = FALSE)
sweep.stats_e135 <- summarizeSweep(sweep.res.list_e135, GT = FALSE)
bcmvn_e135 <- find.pK(sweep.stats_e135)
opt_pK <- as.numeric(as.vector(bcmvn_e135$pK[which.max(bcmvn_e135$BCmetric)]))
print(opt_pK)
annotations <- e135@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)
nExp_poi <- round(0.06*nrow(e135@meta.data))
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
e135 <- doubletFinder_v3(e135,PCs = 1:30,pN = 0.25,pK = opt_pK,nExp = nExp_poi,reuse.pANN = FALSE,sct = FALSE)
name <- colnames(e135@meta.data)[7]
Idents(e135) <- name
e135 <- subset(e135, idents = "Singlet")
saveRDS(e135, file = "e135_goat_clean.rds")

#### d0 pretreatment ###
#### Setup the Seurat objects ### 
d0.data <- Read10X(data.dir = "/cellranger_results_goat_V1/d0/")
d0 <- CreateSeuratObject(counts = d0.data, project = "d0", min.cells = 3, min.features = 200)
samInfo <- rep("d0",nrow(d0@meta.data))
d0 <- AddMetaData(object = d0, metadata = samInfo, col.name = "samInfo")
d0[["ND6"]] <- PercentageFeatureSet(d0, assay = "RNA", feature = "ND6")
d0[["ND5"]] <- PercentageFeatureSet(d0, assay = "RNA", feature = "ND5")
d0[["ND4L"]] <- PercentageFeatureSet(d0, assay = "RNA", feature = "ND4L")
d0[["ND4"]] <- PercentageFeatureSet(d0, assay = "RNA", feature = "ND4")
d0[["ND3"]] <- PercentageFeatureSet(d0, assay = "RNA", feature = "ND3")
d0[["ND2"]] <- PercentageFeatureSet(d0, assay = "RNA", feature = "ND2")
d0[["ND1"]] <- PercentageFeatureSet(d0, assay = "RNA", feature = "ND1")
d0[["CYTB"]] <- PercentageFeatureSet(d0, assay = "RNA", feature = "CYTB")
d0[["COX3"]] <- PercentageFeatureSet(d0, assay = "RNA", feature = "COX3")
d0[["COX2"]] <- PercentageFeatureSet(d0, assay = "RNA", feature = "COX2")
d0[["COX1"]] <- PercentageFeatureSet(d0, assay = "RNA", feature = "COX1")
d0[["ATP8"]] <- PercentageFeatureSet(d0, assay = "RNA", feature = "ATP8")
d0[["ATP6"]] <- PercentageFeatureSet(d0, assay = "RNA", feature = "ATP6")
d0[["percent.mt"]] <- apply(d0@meta.data[,5:15], 1, sum)
VlnPlot(d0, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
d0 <- subset(d0, subset = nFeature_RNA > 200 & nFeature_RNA < 3000 & percent.mt < 20)
plot1 <- FeatureScatter(d0, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(d0, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
d0 <- NormalizeData(d0, normalization.method = "LogNormalize", scale.factor = 10000)
d0 <- FindVariableFeatures(d0, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(d0)
d0 <- ScaleData(d0, features = all.genes)
d0 <- ScaleData(d0, vars.to.regress = "percent.mt")
d0 <- RunPCA(d0, features = VariableFeatures(object = d0))
ElbowPlot(d0, ndim=50)
d0 <- FindNeighbors(d0, dims = 1:30)
d0 <- FindClusters(d0, resolution = 0.6)
d0 <- RunTSNE(d0, dims = 1:30)
DimPlot(d0,reduction = "tsne",label = TRUE, pt.size = 1.5)
d0<- CellCycleScoring(object = d0, g2m.features = cc.genes$g2m.genes, s.features = cc.genes$s.genes)
head(x = d0@meta.data)
DimPlot(d0,reduction = "tsne",label = TRUE,group.by="Phase",pt.size = 1.5)

######Removal of double cells####
library(DoubletFinder)

sweep.res.list_d0 <- paramSweep_v3(d0, PCs = 1:30, sct = FALSE)
sweep.stats_d0 <- summarizeSweep(sweep.res.list_d0, GT = FALSE)
bcmvn_d0 <- find.pK(sweep.stats_d0)
opt_pK <- as.numeric(as.vector(bcmvn_d0$pK[which.max(bcmvn_d0$BCmetric)]))
print(opt_pK)
annotations <- d0@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)
nExp_poi <- round(0.06*nrow(d0@meta.data))
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
d0 <- doubletFinder_v3(d0,PCs = 1:30,pN = 0.25,pK = opt_pK,nExp = nExp_poi,reuse.pANN = FALSE,sct = FALSE)
name <- colnames(d0@meta.data)[7]
Idents(d0) <- name
d0 <- subset(d0, idents = "Singlet")
saveRDS(d0, file = "d0_goat_clean.rds")

#### d7 pretreatment ###
#### Setup the Seurat objects ###

d7.data <- Read10X(data.dir = "/cellranger_results_goat_V1/d7/")
d7 <- CreateSeuratObject(counts = d7.data, project = "d7", min.cells = 3, min.features = 200)
samInfo <- rep("d7",nrow(d7@meta.data))
d7 <- AddMetaData(object = d7, metadata = samInfo, col.name = "samInfo")
d7[["ND6"]] <- PercentageFeatureSet(d7, assay = "RNA", feature = "ND6")
d7[["ND5"]] <- PercentageFeatureSet(d7, assay = "RNA", feature = "ND5")
d7[["ND4L"]] <- PercentageFeatureSet(d7, assay = "RNA", feature = "ND4L")
d7[["ND4"]] <- PercentageFeatureSet(d7, assay = "RNA", feature = "ND4")
d7[["ND3"]] <- PercentageFeatureSet(d7, assay = "RNA", feature = "ND3")
d7[["ND2"]] <- PercentageFeatureSet(d7, assay = "RNA", feature = "ND2")
d7[["ND1"]] <- PercentageFeatureSet(d7, assay = "RNA", feature = "ND1")
d7[["CYTB"]] <- PercentageFeatureSet(d7, assay = "RNA", feature = "CYTB")
d7[["COX3"]] <- PercentageFeatureSet(d7, assay = "RNA", feature = "COX3")
d7[["COX2"]] <- PercentageFeatureSet(d7, assay = "RNA", feature = "COX2")
d7[["COX1"]] <- PercentageFeatureSet(d7, assay = "RNA", feature = "COX1")
d7[["ATP8"]] <- PercentageFeatureSet(d7, assay = "RNA", feature = "ATP8")
d7[["ATP6"]] <- PercentageFeatureSet(d7, assay = "RNA", feature = "ATP6")
d7[["percent.mt"]] <- apply(d7@meta.data[,5:15], 1, sum)
VlnPlot(d7, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
d7 <- subset(d7, subset = nFeature_RNA > 200 & nFeature_RNA < 3000 & percent.mt < 30)
plot1 <- FeatureScatter(d7, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(d7, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
d7 <- NormalizeData(d7, normalization.method = "LogNormalize", scale.factor = 10000)
d7 <- FindVariableFeatures(d7, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(d7)
d7 <- ScaleData(d7, features = all.genes)
d7 <- ScaleData(d7, vars.to.regress = "percent.mt")
d7 <- RunPCA(d7, features = VariableFeatures(object = d7))
ElbowPlot(d7, ndim=50)
d7 <- FindNeighbors(d7, dims = 1:30)
d7 <- FindClusters(d7, resolution = 0.6)
d7 <- RunTSNE(d7, dims = 1:30)
DimPlot(d7,reduction = "tsne",label = TRUE, pt.size = 1.5)
d7<- CellCycleScoring(object = d7, g2m.features = cc.genes$g2m.genes, s.features = cc.genes$s.genes)
head(x = d7@meta.data)
DimPlot(d7,reduction = "tsne",label = TRUE,group.by="Phase",pt.size = 1.5)

######Removal of double cells####
library(DoubletFinder)

sweep.res.list_d7 <- paramSweep_v3(d7, PCs = 1:30, sct = FALSE)
sweep.stats_d7 <- summarizeSweep(sweep.res.list_d7, GT = FALSE)
bcmvn_d7 <- find.pK(sweep.stats_d7)
opt_pK <- as.numeric(as.vector(bcmvn_d7$pK[which.max(bcmvn_d7$BCmetric)]))
print(opt_pK)
annotations <- d7@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)
nExp_poi <- round(0.06*nrow(d7@meta.data))
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
d7 <- doubletFinder_v3(d7,PCs = 1:30,pN = 0.25,pK = opt_pK,nExp = nExp_poi,reuse.pANN = FALSE,sct = FALSE)
name <- colnames(d7@meta.data)[7]
Idents(d7) <- name
d7 <- subset(d7, idents = "Singlet")
saveRDS(d7, file = "d7_goat_clean.rds")

#### d14 pretreatment ###
#### Setup the Seurat objects ###

d14.data <- Read10X(data.dir = "/cellranger_results_goat_V1/d14/")
d14 <- CreateSeuratObject(counts = d14.data, project = "d14", min.cells = 3, min.features = 200)
samInfo <- rep("d14",nrow(d14@meta.data))
d14 <- AddMetaData(object = d14, metadata = samInfo, col.name = "samInfo")
d14[["ND6"]] <- PercentageFeatureSet(d14, assay = "RNA", feature = "ND6")
d14[["ND5"]] <- PercentageFeatureSet(d14, assay = "RNA", feature = "ND5")
d14[["ND4L"]] <- PercentageFeatureSet(d14, assay = "RNA", feature = "ND4L")
d14[["ND4"]] <- PercentageFeatureSet(d14, assay = "RNA", feature = "ND4")
d14[["ND3"]] <- PercentageFeatureSet(d14, assay = "RNA", feature = "ND3")
d14[["ND2"]] <- PercentageFeatureSet(d14, assay = "RNA", feature = "ND2")
d14[["ND1"]] <- PercentageFeatureSet(d14, assay = "RNA", feature = "ND1")
d14[["CYTB"]] <- PercentageFeatureSet(d14, assay = "RNA", feature = "CYTB")
d14[["COX3"]] <- PercentageFeatureSet(d14, assay = "RNA", feature = "COX3")
d14[["COX2"]] <- PercentageFeatureSet(d14, assay = "RNA", feature = "COX2")
d14[["COX1"]] <- PercentageFeatureSet(d14, assay = "RNA", feature = "COX1")
d14[["ATP8"]] <- PercentageFeatureSet(d14, assay = "RNA", feature = "ATP8")
d14[["ATP6"]] <- PercentageFeatureSet(d14, assay = "RNA", feature = "ATP6")
d14[["percent.mt"]] <- apply(d14@meta.data[,5:15], 1, sum)
VlnPlot(d14, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
d14 <- subset(d14, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 50)
plot1 <- FeatureScatter(d14, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(d14, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
d14 <- NormalizeData(d14, normalization.method = "LogNormalize", scale.factor = 10000)
d14 <- FindVariableFeatures(d14, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(d14)
d14 <- ScaleData(d14, features = all.genes)
d14 <- ScaleData(d14, vars.to.regress = "percent.mt")
d14 <- RunPCA(d14, features = VariableFeatures(object = d14))
ElbowPlot(d14, ndim=50)
d14 <- FindNeighbors(d14, dims = 1:30)
d14 <- FindClusters(d14, resolution = 0.6)
d14 <- RunTSNE(d14, dims = 1:30)
DimPlot(d14,reduction = "tsne",label = TRUE, pt.size = 1.5)
d14<- CellCycleScoring(object = d14, g2m.features = cc.genes$g2m.genes, s.features = cc.genes$s.genes)
head(x = d14@meta.data)
DimPlot(d14,reduction = "tsne",label = TRUE,group.by="Phase",pt.size = 1.5)

######Removal of double cells####
library(DoubletFinder)

sweep.res.list_d14 <- paramSweep_v3(d14, PCs = 1:30, sct = FALSE)
sweep.stats_d14 <- summarizeSweep(sweep.res.list_d14, GT = FALSE)
bcmvn_d14 <- find.pK(sweep.stats_d14)
opt_pK <- as.numeric(as.vector(bcmvn_d14$pK[which.max(bcmvn_d14$BCmetric)]))
print(opt_pK)
annotations <- d14@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)
nExp_poi <- round(0.06*nrow(d14@meta.data))
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
d14 <- doubletFinder_v3(d14,PCs = 1:30,pN = 0.25,pK = opt_pK,nExp = nExp_poi,reuse.pANN = FALSE,sct = FALSE)
name <- colnames(d14@meta.data)[7]
Idents(d14) <- name
d14 <- subset(d14, idents = "Singlet")
saveRDS(d14, file = "d14_goat_clean.rds")

#### d21 pretreatment ###
#### Setup the Seurat objects ###

d21.data <- Read10X(data.dir = "/cellranger_results_goat_V1/d21/")
d21 <- CreateSeuratObject(counts = d21.data, project = "d21", min.cells = 3, min.features = 200)
samInfo <- rep("d21",nrow(d21@meta.data))
d21 <- AddMetaData(object = d21, metadata = samInfo, col.name = "samInfo")
d21[["ND6"]] <- PercentageFeatureSet(d21, assay = "RNA", feature = "ND6")
d21[["ND5"]] <- PercentageFeatureSet(d21, assay = "RNA", feature = "ND5")
d21[["ND4L"]] <- PercentageFeatureSet(d21, assay = "RNA", feature = "ND4L")
d21[["ND4"]] <- PercentageFeatureSet(d21, assay = "RNA", feature = "ND4")
d21[["ND3"]] <- PercentageFeatureSet(d21, assay = "RNA", feature = "ND3")
d21[["ND2"]] <- PercentageFeatureSet(d21, assay = "RNA", feature = "ND2")
d21[["ND1"]] <- PercentageFeatureSet(d21, assay = "RNA", feature = "ND1")
d21[["CYTB"]] <- PercentageFeatureSet(d21, assay = "RNA", feature = "CYTB")
d21[["COX3"]] <- PercentageFeatureSet(d21, assay = "RNA", feature = "COX3")
d21[["COX2"]] <- PercentageFeatureSet(d21, assay = "RNA", feature = "COX2")
d21[["COX1"]] <- PercentageFeatureSet(d21, assay = "RNA", feature = "COX1")
d21[["ATP8"]] <- PercentageFeatureSet(d21, assay = "RNA", feature = "ATP8")
d21[["ATP6"]] <- PercentageFeatureSet(d21, assay = "RNA", feature = "ATP6")
d21[["percent.mt"]] <- apply(d21@meta.data[,5:15], 1, sum)
VlnPlot(d21, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
d21 <- subset(d21, subset = nFeature_RNA > 200 & nFeature_RNA < 3000 & percent.mt < 50)
plot1 <- FeatureScatter(d21, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(d21, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
d21 <- NormalizeData(d21, normalization.method = "LogNormalize", scale.factor = 10000)
d21 <- FindVariableFeatures(d21, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(d21)
d21 <- ScaleData(d21, features = all.genes)
d21 <- ScaleData(d21, vars.to.regress = "percent.mt")
d21 <- RunPCA(d21, features = VariableFeatures(object = d21))
ElbowPlot(d21, ndim=50)
d21 <- FindNeighbors(d21, dims = 1:30)
d21 <- FindClusters(d21, resolution = 0.6)
d21 <- RunTSNE(d21, dims = 1:30)
DimPlot(d21,reduction = "tsne",label = TRUE, pt.size = 1.5)
d21<- CellCycleScoring(object = d21, g2m.features = cc.genes$g2m.genes, s.features = cc.genes$s.genes)
head(x = d21@meta.data)
DimPlot(d21,reduction = "tsne",label = TRUE,group.by="Phase",pt.size = 1.5)

######Removal of double cells####
library(DoubletFinder)

sweep.res.list_d21 <- paramSweep_v3(d21, PCs = 1:30, sct = FALSE)
sweep.stats_d21 <- summarizeSweep(sweep.res.list_d21, GT = FALSE)
bcmvn_d21 <- find.pK(sweep.stats_d21)
opt_pK <- as.numeric(as.vector(bcmvn_d21$pK[which.max(bcmvn_d21$BCmetric)]))
print(opt_pK)
annotations <- d21@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)
nExp_poi <- round(0.06*nrow(d21@meta.data))
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
d21 <- doubletFinder_v3(d21,PCs = 1:30,pN = 0.25,pK = opt_pK,nExp = nExp_poi,reuse.pANN = FALSE,sct = FALSE)
name <- colnames(d21@meta.data)[7]
Idents(d21) <- name
d21 <- subset(d21, idents = "Singlet")
saveRDS(d21, file = "d21_goat_clean.rds")

#### d28 pretreatment ###
#### Setup the Seurat objects ###

d28.data <- Read10X(data.dir = "/cellranger_results_goat_V1/d28/")
d28 <- CreateSeuratObject(counts = d28.data, project = "d28", min.cells = 3, min.features = 200)
samInfo <- rep("d28",nrow(d28@meta.data))
d28 <- AddMetaData(object = d28, metadata = samInfo, col.name = "samInfo")
d28[["ND6"]] <- PercentageFeatureSet(d28, assay = "RNA", feature = "ND6")
d28[["ND5"]] <- PercentageFeatureSet(d28, assay = "RNA", feature = "ND5")
d28[["ND4L"]] <- PercentageFeatureSet(d28, assay = "RNA", feature = "ND4L")
d28[["ND4"]] <- PercentageFeatureSet(d28, assay = "RNA", feature = "ND4")
d28[["ND3"]] <- PercentageFeatureSet(d28, assay = "RNA", feature = "ND3")
d28[["ND2"]] <- PercentageFeatureSet(d28, assay = "RNA", feature = "ND2")
d28[["ND1"]] <- PercentageFeatureSet(d28, assay = "RNA", feature = "ND1")
d28[["CYTB"]] <- PercentageFeatureSet(d28, assay = "RNA", feature = "CYTB")
d28[["COX3"]] <- PercentageFeatureSet(d28, assay = "RNA", feature = "COX3")
d28[["COX2"]] <- PercentageFeatureSet(d28, assay = "RNA", feature = "COX2")
d28[["COX1"]] <- PercentageFeatureSet(d28, assay = "RNA", feature = "COX1")
d28[["ATP8"]] <- PercentageFeatureSet(d28, assay = "RNA", feature = "ATP8")
d28[["ATP6"]] <- PercentageFeatureSet(d28, assay = "RNA", feature = "ATP6")
d28[["percent.mt"]] <- apply(d28@meta.data[,5:15], 1, sum)
VlnPlot(d28, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
d28 <- subset(d28, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 60)
plot1 <- FeatureScatter(d28, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(d28, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
d28 <- NormalizeData(d28, normalization.method = "LogNormalize", scale.factor = 10000)
d28 <- FindVariableFeatures(d28, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(d28)
d28 <- ScaleData(d28, features = all.genes)
d28 <- ScaleData(d28, vars.to.regress = "percent.mt")
d28 <- RunPCA(d28, features = VariableFeatures(object = d28))
ElbowPlot(d28, ndim=50)
d28 <- FindNeighbors(d28, dims = 1:30)
d28 <- FindClusters(d28, resolution = 0.6)
d28 <- RunTSNE(d28, dims = 1:30)
DimPlot(d28,reduction = "tsne",label = TRUE, pt.size = 1.5)
d28<- CellCycleScoring(object = d28, g2m.features = cc.genes$g2m.genes, s.features = cc.genes$s.genes)
head(x = d28@meta.data)
DimPlot(d28,reduction = "tsne",label = TRUE,group.by="Phase",pt.size = 1.5)

######Removal of double cells####
library(DoubletFinder)

sweep.res.list_d28 <- paramSweep_v3(d28, PCs = 1:30, sct = FALSE)
sweep.stats_d28 <- summarizeSweep(sweep.res.list_d28, GT = FALSE)
bcmvn_d28 <- find.pK(sweep.stats_d28)
opt_pK <- as.numeric(as.vector(bcmvn_d28$pK[which.max(bcmvn_d28$BCmetric)]))
print(opt_pK)
annotations <- d28@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)
nExp_poi <- round(0.06*nrow(d28@meta.data))
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
d28 <- doubletFinder_v3(d28,PCs = 1:30,pN = 0.25,pK = opt_pK,nExp = nExp_poi,reuse.pANN = FALSE,sct = FALSE)
name <- colnames(d28@meta.data)[7]
Idents(d28) <- name
d28 <- subset(d28, idents = "Singlet")
saveRDS(d28, file = "d28_goat_clean.rds")

#### d35 pretreatment ###
#### Setup the Seurat objects ###

d35.data <- Read10X(data.dir = "/cellranger_results_goat_V1/d35/")
d35 <- CreateSeuratObject(counts = d35.data, project = "d35", min.cells = 3, min.features = 200)
samInfo <- rep("d35",nrow(d35@meta.data))
d35 <- AddMetaData(object = d35, metadata = samInfo, col.name = "samInfo")
d35[["ND6"]] <- PercentageFeatureSet(d35, assay = "RNA", feature = "ND6")
d35[["ND5"]] <- PercentageFeatureSet(d35, assay = "RNA", feature = "ND5")
d35[["ND4L"]] <- PercentageFeatureSet(d35, assay = "RNA", feature = "ND4L")
d35[["ND4"]] <- PercentageFeatureSet(d35, assay = "RNA", feature = "ND4")
d35[["ND3"]] <- PercentageFeatureSet(d35, assay = "RNA", feature = "ND3")
d35[["ND2"]] <- PercentageFeatureSet(d35, assay = "RNA", feature = "ND2")
d35[["ND1"]] <- PercentageFeatureSet(d35, assay = "RNA", feature = "ND1")
d35[["CYTB"]] <- PercentageFeatureSet(d35, assay = "RNA", feature = "CYTB")
d35[["COX3"]] <- PercentageFeatureSet(d35, assay = "RNA", feature = "COX3")
d35[["COX2"]] <- PercentageFeatureSet(d35, assay = "RNA", feature = "COX2")
d35[["COX1"]] <- PercentageFeatureSet(d35, assay = "RNA", feature = "COX1")
d35[["ATP8"]] <- PercentageFeatureSet(d35, assay = "RNA", feature = "ATP8")
d35[["ATP6"]] <- PercentageFeatureSet(d35, assay = "RNA", feature = "ATP6")
d35[["percent.mt"]] <- apply(d35@meta.data[,5:15], 1, sum)
VlnPlot(d35, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
d35 <- subset(d35, subset = nFeature_RNA > 200 & nFeature_RNA < 3500 & percent.mt < 40)
plot1 <- FeatureScatter(d35, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(d35, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
d35 <- NormalizeData(d35, normalization.method = "LogNormalize", scale.factor = 10000)
d35 <- FindVariableFeatures(d35, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(d35)
d35 <- ScaleData(d35, features = all.genes)
d35 <- ScaleData(d35, vars.to.regress = "percent.mt")
d35 <- RunPCA(d35, features = VariableFeatures(object = d35))
ElbowPlot(d35, ndim=50)
d35 <- FindNeighbors(d35, dims = 1:30)
d35 <- FindClusters(d35, resolution = 0.6)
d35 <- RunTSNE(d35, dims = 1:30)
DimPlot(d35,reduction = "tsne",label = TRUE, pt.size = 1.5)
d35<- CellCycleScoring(object = d35, g2m.features = cc.genes$g2m.genes, s.features = cc.genes$s.genes)
head(x = d35@meta.data)
DimPlot(d35,reduction = "tsne",label = TRUE,group.by="Phase",pt.size = 1.5)

######Removal of double cells####
library(DoubletFinder)

sweep.res.list_d35 <- paramSweep_v3(d35, PCs = 1:30, sct = FALSE)
sweep.stats_d35 <- summarizeSweep(sweep.res.list_d35, GT = FALSE)
bcmvn_d35 <- find.pK(sweep.stats_d35)
opt_pK <- as.numeric(as.vector(bcmvn_d35$pK[which.max(bcmvn_d35$BCmetric)]))
print(opt_pK)
annotations <- d35@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)
nExp_poi <- round(0.06*nrow(d35@meta.data))
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
d35 <- doubletFinder_v3(d35,PCs = 1:30,pN = 0.25,pK = opt_pK,nExp = nExp_poi,reuse.pANN = FALSE,sct = FALSE)
name <- colnames(d35@meta.data)[7]
Idents(d35) <- name
d35 <- subset(d35, idents = "Singlet")
saveRDS(d35, file = "d35_goat_clean.rds")

#### d42 pretreatment ###
#### Setup the Seurat objects ###

d42.data <- Read10X(data.dir = "/cellranger_results_goat_V1/d42/")
d42 <- CreateSeuratObject(counts = d42.data, project = "d42", min.cells = 3, min.features = 200)
samInfo <- rep("d42",nrow(d42@meta.data))
d42 <- AddMetaData(object = d42, metadata = samInfo, col.name = "samInfo")
d42[["ND6"]] <- PercentageFeatureSet(d42, assay = "RNA", feature = "ND6")
d42[["ND5"]] <- PercentageFeatureSet(d42, assay = "RNA", feature = "ND5")
d42[["ND4L"]] <- PercentageFeatureSet(d42, assay = "RNA", feature = "ND4L")
d42[["ND4"]] <- PercentageFeatureSet(d42, assay = "RNA", feature = "ND4")
d42[["ND3"]] <- PercentageFeatureSet(d42, assay = "RNA", feature = "ND3")
d42[["ND2"]] <- PercentageFeatureSet(d42, assay = "RNA", feature = "ND2")
d42[["ND1"]] <- PercentageFeatureSet(d42, assay = "RNA", feature = "ND1")
d42[["CYTB"]] <- PercentageFeatureSet(d42, assay = "RNA", feature = "CYTB")
d42[["COX3"]] <- PercentageFeatureSet(d42, assay = "RNA", feature = "COX3")
d42[["COX2"]] <- PercentageFeatureSet(d42, assay = "RNA", feature = "COX2")
d42[["COX1"]] <- PercentageFeatureSet(d42, assay = "RNA", feature = "COX1")
d42[["ATP8"]] <- PercentageFeatureSet(d42, assay = "RNA", feature = "ATP8")
d42[["ATP6"]] <- PercentageFeatureSet(d42, assay = "RNA", feature = "ATP6")
d42[["percent.mt"]] <- apply(d42@meta.data[,5:15], 1, sum)
VlnPlot(d42, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
d42 <- subset(d42, subset = nFeature_RNA > 200 & nFeature_RNA < 3000 & percent.mt < 60)
plot1 <- FeatureScatter(d42, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(d42, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
d42 <- NormalizeData(d42, normalization.method = "LogNormalize", scale.factor = 10000)
d42 <- FindVariableFeatures(d42, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(d42)
d42 <- ScaleData(d42, features = all.genes)
d42 <- ScaleData(d42, vars.to.regress = "percent.mt")
d42 <- RunPCA(d42, features = VariableFeatures(object = d42))
ElbowPlot(d42, ndim=50)
d42 <- FindNeighbors(d42, dims = 1:30)
d42 <- FindClusters(d42, resolution = 0.6)
d42 <- RunTSNE(d42, dims = 1:30)
DimPlot(d42,reduction = "tsne",label = TRUE, pt.size = 1.5)
d42<- CellCycleScoring(object = d42, g2m.features = cc.genes$g2m.genes, s.features = cc.genes$s.genes)
head(x = d42@meta.data)
DimPlot(d42,reduction = "tsne",label = TRUE,group.by="Phase",pt.size = 1.5)

######Removal of double cells####
library(DoubletFinder)

sweep.res.list_d42 <- paramSweep_v3(d42, PCs = 1:30, sct = FALSE)
sweep.stats_d42 <- summarizeSweep(sweep.res.list_d42, GT = FALSE)
bcmvn_d42 <- find.pK(sweep.stats_d42)
opt_pK <- as.numeric(as.vector(bcmvn_d42$pK[which.max(bcmvn_d42$BCmetric)]))
print(opt_pK)
annotations <- d42@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)
nExp_poi <- round(0.06*nrow(d42@meta.data))
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
d42 <- doubletFinder_v3(d42,PCs = 1:30,pN = 0.25,pK = opt_pK,nExp = nExp_poi,reuse.pANN = FALSE,sct = FALSE)
name <- colnames(d42@meta.data)[7]
Idents(d42) <- name
d42 <- subset(d42, idents = "Singlet")
saveRDS(d42, file = "d42_goat_clean.rds")

#### d49 pretreatment ###
#### Setup the Seurat objects ###

d49.data <- Read10X(data.dir = "/cellranger_results_goat_V1/d49/")
d49 <- CreateSeuratObject(counts = d49.data, project = "d49", min.cells = 3, min.features = 200)
samInfo <- rep("d49",nrow(d49@meta.data))
d49 <- AddMetaData(object = d49, metadata = samInfo, col.name = "samInfo")
d49[["ND6"]] <- PercentageFeatureSet(d49, assay = "RNA", feature = "ND6")
d49[["ND5"]] <- PercentageFeatureSet(d49, assay = "RNA", feature = "ND5")
d49[["ND4L"]] <- PercentageFeatureSet(d49, assay = "RNA", feature = "ND4L")
d49[["ND4"]] <- PercentageFeatureSet(d49, assay = "RNA", feature = "ND4")
d49[["ND3"]] <- PercentageFeatureSet(d49, assay = "RNA", feature = "ND3")
d49[["ND2"]] <- PercentageFeatureSet(d49, assay = "RNA", feature = "ND2")
d49[["ND1"]] <- PercentageFeatureSet(d49, assay = "RNA", feature = "ND1")
d49[["CYTB"]] <- PercentageFeatureSet(d49, assay = "RNA", feature = "CYTB")
d49[["COX3"]] <- PercentageFeatureSet(d49, assay = "RNA", feature = "COX3")
d49[["COX2"]] <- PercentageFeatureSet(d49, assay = "RNA", feature = "COX2")
d49[["COX1"]] <- PercentageFeatureSet(d49, assay = "RNA", feature = "COX1")
d49[["ATP8"]] <- PercentageFeatureSet(d49, assay = "RNA", feature = "ATP8")
d49[["ATP6"]] <- PercentageFeatureSet(d49, assay = "RNA", feature = "ATP6")
d49[["percent.mt"]] <- apply(d49@meta.data[,5:15], 1, sum)
VlnPlot(d49, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
d49 <- subset(d49, subset = nFeature_RNA > 200 & nFeature_RNA < 3500 & percent.mt < 70)
plot1 <- FeatureScatter(d49, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(d49, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
d49 <- NormalizeData(d49, normalization.method = "LogNormalize", scale.factor = 10000)
d49 <- FindVariableFeatures(d49, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(d49)
d49 <- ScaleData(d49, features = all.genes)
d49 <- ScaleData(d49, vars.to.regress = "percent.mt")
d49 <- RunPCA(d49, features = VariableFeatures(object = d49))
ElbowPlot(d49, ndim=50)
d49 <- FindNeighbors(d49, dims = 1:30)
d49 <- FindClusters(d49, resolution = 0.6)
d49 <- RunTSNE(d49, dims = 1:30)
DimPlot(d49,reduction = "tsne",label = TRUE, pt.size = 1.5)
d49<- CellCycleScoring(object = d49, g2m.features = cc.genes$g2m.genes, s.features = cc.genes$s.genes)
head(x = d49@meta.data)
DimPlot(d49,reduction = "tsne",label = TRUE,group.by="Phase",pt.size = 1.5)

######Removal of double cells####
library(DoubletFinder)

sweep.res.list_d49 <- paramSweep_v3(d49, PCs = 1:30, sct = FALSE)
sweep.stats_d49 <- summarizeSweep(sweep.res.list_d49, GT = FALSE)
bcmvn_d49 <- find.pK(sweep.stats_d49)
opt_pK <- as.numeric(as.vector(bcmvn_d49$pK[which.max(bcmvn_d49$BCmetric)]))
print(opt_pK)
annotations <- d49@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)
nExp_poi <- round(0.06*nrow(d49@meta.data))
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
d49 <- doubletFinder_v3(d49,PCs = 1:30,pN = 0.25,pK = opt_pK,nExp = nExp_poi,reuse.pANN = FALSE,sct = FALSE)
name <- colnames(d49@meta.data)[7]
Idents(d49) <- name
d49 <- subset(d49, idents = "Singlet")
saveRDS(d49, file = "d49_goat_clean.rds")

#### d56 pretreatment ###
#### Setup the Seurat objects ###

d56.data <- Read10X(data.dir = "/cellranger_results_goat_V1/d56/")
d56 <- CreateSeuratObject(counts = d56.data, project = "d56", min.cells = 3, min.features = 200)
samInfo <- rep("d56",nrow(d56@meta.data))
d56 <- AddMetaData(object = d56, metadata = samInfo, col.name = "samInfo")
d56[["ND6"]] <- PercentageFeatureSet(d56, assay = "RNA", feature = "ND6")
d56[["ND5"]] <- PercentageFeatureSet(d56, assay = "RNA", feature = "ND5")
d56[["ND4L"]] <- PercentageFeatureSet(d56, assay = "RNA", feature = "ND4L")
d56[["ND4"]] <- PercentageFeatureSet(d56, assay = "RNA", feature = "ND4")
d56[["ND3"]] <- PercentageFeatureSet(d56, assay = "RNA", feature = "ND3")
d56[["ND2"]] <- PercentageFeatureSet(d56, assay = "RNA", feature = "ND2")
d56[["ND1"]] <- PercentageFeatureSet(d56, assay = "RNA", feature = "ND1")
d56[["CYTB"]] <- PercentageFeatureSet(d56, assay = "RNA", feature = "CYTB")
d56[["COX3"]] <- PercentageFeatureSet(d56, assay = "RNA", feature = "COX3")
d56[["COX2"]] <- PercentageFeatureSet(d56, assay = "RNA", feature = "COX2")
d56[["COX1"]] <- PercentageFeatureSet(d56, assay = "RNA", feature = "COX1")
d56[["ATP8"]] <- PercentageFeatureSet(d56, assay = "RNA", feature = "ATP8")
d56[["ATP6"]] <- PercentageFeatureSet(d56, assay = "RNA", feature = "ATP6")
d56[["percent.mt"]] <- apply(d56@meta.data[,5:15], 1, sum)
VlnPlot(d56, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
d56 <- subset(d56, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 60)
plot1 <- FeatureScatter(d56, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(d56, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
d56 <- NormalizeData(d56, normalization.method = "LogNormalize", scale.factor = 10000)
d56 <- FindVariableFeatures(d56, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(d56)
d56 <- ScaleData(d56, features = all.genes)
d56 <- ScaleData(d56, vars.to.regress = "percent.mt")
d56 <- RunPCA(d56, features = VariableFeatures(object = d56))
ElbowPlot(d56, ndim=50)
d56 <- FindNeighbors(d56, dims = 1:30)
d56 <- FindClusters(d56, resolution = 0.6)
d56 <- RunTSNE(d56, dims = 1:30)
DimPlot(d56,reduction = "tsne",label = TRUE, pt.size = 1.5)
d56<- CellCycleScoring(object = d56, g2m.features = cc.genes$g2m.genes, s.features = cc.genes$s.genes)
head(x = d56@meta.data)
DimPlot(d56,reduction = "tsne",label = TRUE,group.by="Phase",pt.size = 1.5)

######Removal of double cells####
library(DoubletFinder)

sweep.res.list_d56 <- paramSweep_v3(d56, PCs = 1:30, sct = FALSE)
sweep.stats_d56 <- summarizeSweep(sweep.res.list_d56, GT = FALSE)
bcmvn_d56 <- find.pK(sweep.stats_d56)
opt_pK <- as.numeric(as.vector(bcmvn_d56$pK[which.max(bcmvn_d56$BCmetric)]))
print(opt_pK)
annotations <- d56@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)
nExp_poi <- round(0.06*nrow(d56@meta.data))
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
d56 <- doubletFinder_v3(d56,PCs = 1:30,pN = 0.25,pK = opt_pK,nExp = nExp_poi,reuse.pANN = FALSE,sct = FALSE)
name <- colnames(d56@meta.data)[7]
Idents(d56) <- name
d56 <- subset(d56, idents = "Singlet")
saveRDS(d56, file = "d56_goat_clean.rds")

#### d90 pretreatment ###
#### Setup the Seurat objects ###

d90.data <- Read10X(data.dir = "/cellranger_results_goat_V1/d90/")
d90 <- CreateSeuratObject(counts = d90.data, project = "d90", min.cells = 3, min.features = 200)
samInfo <- rep("d90",nrow(d90@meta.data))
d90 <- AddMetaData(object = d90, metadata = samInfo, col.name = "samInfo")
d90[["ND6"]] <- PercentageFeatureSet(d90, assay = "RNA", feature = "ND6")
d90[["ND5"]] <- PercentageFeatureSet(d90, assay = "RNA", feature = "ND5")
d90[["ND4L"]] <- PercentageFeatureSet(d90, assay = "RNA", feature = "ND4L")
d90[["ND4"]] <- PercentageFeatureSet(d90, assay = "RNA", feature = "ND4")
d90[["ND3"]] <- PercentageFeatureSet(d90, assay = "RNA", feature = "ND3")
d90[["ND2"]] <- PercentageFeatureSet(d90, assay = "RNA", feature = "ND2")
d90[["ND1"]] <- PercentageFeatureSet(d90, assay = "RNA", feature = "ND1")
d90[["CYTB"]] <- PercentageFeatureSet(d90, assay = "RNA", feature = "CYTB")
d90[["COX3"]] <- PercentageFeatureSet(d90, assay = "RNA", feature = "COX3")
d90[["COX2"]] <- PercentageFeatureSet(d90, assay = "RNA", feature = "COX2")
d90[["COX1"]] <- PercentageFeatureSet(d90, assay = "RNA", feature = "COX1")
d90[["ATP8"]] <- PercentageFeatureSet(d90, assay = "RNA", feature = "ATP8")
d90[["ATP6"]] <- PercentageFeatureSet(d90, assay = "RNA", feature = "ATP6")
d90[["percent.mt"]] <- apply(d90@meta.data[,5:15], 1, sum)
VlnPlot(d90, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
d90 <- subset(d90, subset = nFeature_RNA > 200 & nFeature_RNA < 3500 & percent.mt < 60)
plot1 <- FeatureScatter(d90, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(d90, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
d90 <- NormalizeData(d90, normalization.method = "LogNormalize", scale.factor = 10000)
d90 <- FindVariableFeatures(d90, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(d90)
d90 <- ScaleData(d90, features = all.genes)
d90 <- ScaleData(d90, vars.to.regress = "percent.mt")
d90 <- RunPCA(d90, features = VariableFeatures(object = d90))
ElbowPlot(d90, ndim=50)
d90 <- FindNeighbors(d90, dims = 1:30)
d90 <- FindClusters(d90, resolution = 0.6)
d90 <- RunTSNE(d90, dims = 1:30)
DimPlot(d90,reduction = "tsne",label = TRUE, pt.size = 1.5)
d90<- CellCycleScoring(object = d90, g2m.features = cc.genes$g2m.genes, s.features = cc.genes$s.genes)
head(x = d90@meta.data)
DimPlot(d90,reduction = "tsne",label = TRUE,group.by="Phase",pt.size = 1.5)

######Removal of double cells####
library(DoubletFinder)

sweep.res.list_d90 <- paramSweep_v3(d90, PCs = 1:30, sct = FALSE)
sweep.stats_d90 <- summarizeSweep(sweep.res.list_d90, GT = FALSE)
bcmvn_d90 <- find.pK(sweep.stats_d90)
opt_pK <- as.numeric(as.vector(bcmvn_d90$pK[which.max(bcmvn_d90$BCmetric)]))
print(opt_pK)
annotations <- d90@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)
nExp_poi <- round(0.06*nrow(d90@meta.data))
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
d90 <- doubletFinder_v3(d90,PCs = 1:30,pN = 0.25,pK = opt_pK,nExp = nExp_poi,reuse.pANN = FALSE,sct = FALSE)
name <- colnames(d90@meta.data)[7]
Idents(d90) <- name
d90 <- subset(d90, idents = "Singlet")
saveRDS(d90, file = "d90_goat_clean.rds")